- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v1.2.3
  hooks:
    - id: trailing-whitespace
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/willthames/ansible-lint.git
  sha: v3.4.20
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
