---
- name: Ensure sensu APT key exists
  apt_key:
    url: https://sensu.global.ssl.fastly.net/apt/pubkey.gpg

- name: Ensure sensu apt config exists
  apt_repository:
    repo: 'deb http://repositories.sensuapp.org/apt sensu main'
