---
- name: Ensure Sensu apt-key exists
  apt_key:
    id: EB9C94BB
    url: https://sensu.global.ssl.fastly.net/apt/pubkey.gpg

- name: Ensure apt-transport-https is installed
  apt:
    name: apt-transport-https
    state: present

- name: Ensure Sensu apt-repo exists
  apt_repository:
    filename: sensu
    repo: 'deb https://repositories.sensuapp.org/apt sensu main'

- name: Ensure Sensu is installed
  apt:
    package: sensu
    state: "{{ sensu_state }}"
  notify: Sensu cleanup
