---
- name: Validate sensu_client_configs variable
  assert:
    that:
      - sensu_client_configs.client is defined

- name: Ensure configs exists
  copy:
    content: "{{ item.key | combine(item.value) | to_nice_json }}"
    dest: "{{ sensu_client_configs_dir}}/{{ item.key }}.json"
    owner: sensu
    group: sensu
    mode: 0660
    validate: '/opt/sensu/bin/sensu-client --validate_config -c %s'
  notify: restart sensu-client
  with_dict: "{{ sensu_client_configs }}"

- name:  Ensure {{ sensu_client_configs.rabbitmq.cert_chain_file }} exists
  template:
    src: cert_chain_file.j2
    dest: "{{ sensu_client_configs.rabbitmq.ssl.cert_chain_file }}"
    owner: sensu
    group: sensu
    mode: 0660
    validate: '/usr/bin/openssl x509 -noout -in %s'
  notify: restart sensu-client
  when:
    - sensu_client_rabbitmq_cert_chain is defined
    - sensu_client_configs.rabbitmq.ssl.cert_chain_file is defined

- name: Ensure {{ sensu_client_configs.rabbitmq.ssl.private_key_file }} exists
  template:
    src: private_key_file.j2
    dest: "{{ sensu_client_configs.rabbitmq.ssl.private_key_file }}"
    owner: sensu
    group: sensu
    mode: 0660
    validate: '/usr/bin/openssl rsa -noout -in %s'
  notify: restart sensu-client
  when:
    - sensu_client_rabbitmq_private_key is defined
    - sensu_client_configs.rabbitmq.ssl.private_key_file is defined
