---
- include: install/apt.yml
  when: ansible_os_family == 'Debian'

- include: install/yum.yml
  when: ansible_os_family == 'RedHat'

- meta: flush_handlers

- name: Ensure sensu-client starts at boot
  service:
    name: sensu-client
    enabled: yes

- include: config.yml

- include: plugins.yml

- name: Check if /tmp/sensu_client_loaded_files exists
  stat:
    path: /tmp/sensu_client_loaded_files
  register: sensu_client_loaded_file

# Works around an install bug where /tmp/sensu_client_loaded_files is owned by root
- name: Ensure /tmp/sensu_client_loaded_files is owned by sensu
  file:
    path: /tmp/sensu_client_loaded_files
    owner: sensu
    group: sensu
    mode: 0660
  changed_when: False
  when: sensu_client_loaded_file.stat.exists

- name: Ensure sensu-client is running
  service:
    name: sensu-client
    state: started
