---
- include_tasks: "{{ ansible_pkg_mgr }}.yml"

- meta: flush_handlers

- name: Ensure sensu-client starts at boot
  service:
    name: sensu-client
    enabled: yes

- name: Ensure client config exists
  template:
    src: client.json.j2
    dest: /etc/sensu/conf.d/client.json
    owner: sensu
    group: sensu
    mode: 0660
    validate: '/opt/sensu/bin/sensu-client --validate_config -c %s'
  notify: restart sensu-client

- name: Ensure client transport config exists
  template:
    src: transport.json.j2
    dest: /etc/sensu/conf.d/transport.json
    owner: sensu
    group: sensu
    mode: 0660
    validate: '/opt/sensu/bin/sensu-client --validate_config -c %s'
  notify: restart sensu-client

- name: Ensure client rabbitmq config exists
  template:
    src: transport.json.j2
    dest: /etc/sensu/conf.d/rabbitmq.json
    owner: sensu
    group: sensu
    mode: 0660
    validate: '/opt/sensu/bin/sensu-client --validate_config -c %s'
  notify: restart sensu-client
  when: sensu_client_transport.name == 'rabbitmq'

- name: Install required gems
  gem:
    executable: /opt/sensu/embedded/bin/gem
    name: "{{ item }}"
    state: present
  with_items: "{{ sensu_client_gems }}"

- name: Ensure checks are installed
  command: sensu-install -p {{ item }}
  register: sensu_install
  changed_when: "'installing Sensu gem' in sensu_install.stdout"
  with_items: "{{ sensu_client_checks }}"

- name: Ensure /tmp/sensu_client_loaded_files is owned by sensu
  file:
    path: /tmp/sensu_client_loaded_files
    owner: sensu
    group: sensu
    mode: 0660

- name: Ensure sensu-client is running
  service:
    name: sensu-client
    state: started
