---
- include: apt.yml
  when: ansible_distribution == 'Debian'

- name: Ensure sensu is installed
  apt: 
    package: sensu 
    state: "{{ sensu_version }}"
  notify: sensu cleanup

- name: Ensure sensu-client starts at boot
  service: 
    name: sensu-client 
    enabled: yes

- name: Ensure client config exists
  template: 
    src: client.json.j2 
    dest: /etc/sensu/conf.d/client.json 
    owner: sensu 
    group: sensu
    mode: 0660
    validate: '/opt/sensu/bin/sensu-client --validate_config -c %s'
  notify: restart sensu-client

- name: Ensure client transport config exists
  template: 
    src: transport.json.j2 
    dest: /etc/sensu/conf.d/transport.json 
    owner: sensu
    group: sensu
    mode: 0660
    validate: '/opt/sensu/bin/sensu-client --validate_config -c %s'
  notify: restart sensu-client

- name: Install required gems
  gem: 
    executable: /opt/sensu/embedded/bin/gem
    name: "{{ item }}"
    state: latest
  with_items: "{{ sensu_client_gems }}" 

- name: Ensure checks are installed 
  command: sensu-install -p {{ item }} 
  register: sensu_install
  changed_when: "'installing Sensu gem' in sensu_install.stdout"
  with_items: "{{ sensu_client_checks }}"

- name: Ensure sensu-client is running
  service: 
    name: sensu-client
    state: started
