---
- include_tasks: "{{ ansible_pkg_mgr }}.yml"

- meta: flush_handlers

- name: Ensure sensu-client starts at boot
  service:
    name: sensu-client
    enabled: yes

- name: Ensure client config exists
  template:
    src: client.json.j2
    dest: /etc/sensu/conf.d/client.json
    owner: sensu
    group: sensu
    mode: 0660
    validate: '/opt/sensu/bin/sensu-client --validate_config -c %s'
  notify: restart sensu-client

- name: Ensure client transport config exists
  template:
    src: transport.json.j2
    dest: /etc/sensu/conf.d/transport.json
    owner: sensu
    group: sensu
    mode: 0660
    validate: '/opt/sensu/bin/sensu-client --validate_config -c %s'
  notify: restart sensu-client

- name: Ensure client rabbitmq config exists
  template:
    src: rabbitmq.json.j2
    dest: /etc/sensu/conf.d/rabbitmq.json
    owner: sensu
    group: sensu
    mode: 0660
    validate: '/opt/sensu/bin/sensu-client --validate_config -c %s'
  notify: restart sensu-client
  when: sensu_client_transport.name == 'rabbitmq'

- name: Ensure client check configs exist
  template:
    src: check.json.j2
    dest: /etc/sensu/conf.d/check_{{ item.key }}.json
    owner: sensu
    group: sensu
    mode: 0660
    validate: '/opt/sensu/bin/sensu-client --validate_config -c %s'
  notify: restart sensu-client
  with_dict: "{{ sensu_client_checks }}"
  when: sensu_client_checks is defined

- name: Ensure client extensions config exists
  template:
    src: extensions.json.j2
    dest: /etc/sensu/conf.d/extensions.json
    owner: sensu
    group: sensu
    mode: 0660
    validate: '/opt/sensu/bin/sensu-client --validate_config -c %s'
  notify: restart sensu-client
  when: sensu_client_extensions_config is defined

- name: Install required gems
  gem:
    executable: /opt/sensu/embedded/bin/gem
    name: "{{ item }}"
    state: present
  with_items: "{{ sensu_client_gems }}"
  when: sensu_client_gems is defined

- name: Ensure plugins are installed
  command: sensu-install --plugin {{ item }}
  register: sensu_install
  changed_when: "'installing Sensu gem' in sensu_install.stdout"
  with_items: "{{ sensu_client_plugins }}"
  when: sensu_client_plugins is defined

- name: Ensure extensions are installed
  command: sensu-install --extension {{ item }}
  register: sensu_install
  changed_when: "'installing Sensu gem' in sensu_install.stdout"
  with_items: "{{ sensu_client_extensions }}"
  when: sensu_client_extensions is defined

- name: Ensure custom source plugins/extensions are installed
  command: sensu-install --source {{ item }}
  register: sensu_install
  changed_when: "'installing Sensu gem' in sensu_install.stdout"
  with_items: "{{ sensu_client_custom_source }}"
  when: sensu_client_custom_source is defined

- name: Ensure /tmp/sensu_client_loaded_files is owned by sensu
  file:
    path: /tmp/sensu_client_loaded_files
    owner: sensu
    group: sensu
    mode: 0660

- name: Ensure {{ sensu_client_rabbitmq.rabbitmq.ssl.cert_chain_file }} exists
  template:
    src: cert_chain_file.j2
    dest: "{{ sensu_client_rabbitmq.rabbitmq.ssl.cert_chain_file }}"
    owner: sensu
    group: sensu
    mode: 0660
    validate: '/usr/bin/openssl x509 -noout -in %s'
  notify: restart sensu-client
  when:
    - sensu_client_rabbitmq_cert_chain is defined
    - sensu_client_rabbitmq.rabbitmq.ssl.cert_chain_file is defined

- name: Ensure {{ sensu_client_rabbitmq.rabbitmq.ssl.private_key_file }} exists
  template:
    src: private_key_file.j2
    dest: "{{ sensu_client_rabbitmq.rabbitmq.ssl.private_key_file }}"
    owner: sensu
    group: sensu
    mode: 0660
    validate: '/usr/bin/openssl rsa -noout -in %s'
  notify: restart sensu-client
  when:
    - sensu_client_rabbitmq_private_key is defined
    - sensu_client_rabbitmq.rabbitmq.ssl.private_key_file is defined

- name: Ensure sensu-client is running
  service:
    name: sensu-client
    state: started
