version: 2.0
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: williamyeh/ansible:debian9
    steps:
      - checkout
      - run:
          name: Install ca-certificates to unfuck restore_cache
          command: |
            apt-get update -qq
            apt-get install -y ca-certificates
      - run:
          name: Install sensu-client deps
          command: |
            apt-get install -y --no-install-recommends procps
      - run:
          name: run tests
          command: |
            mkdir -p /etc/ansible/roles/sensu-client && cp -r ~/repo/* /etc/ansible/roles/sensu-client/
            cd tests/
            ansible-playbook -v --connection=local -i localhost, playbook.yml
