version: 2.0
jobs:
  debian9:
    working_directory: /etc/ansible/roles/sensu-client/
    docker:
      - image: williamyeh/ansible:debian9
    steps:
      - checkout
      - run:
          name: Install sensu-client deps
          command: apt-get install -y --no-install-recommends procps
      - run:
          name: run tests
          command: |
            ansible-playbook -v --connection=local -i localhost, tests/playbook.yml
  centos7:
    working_directory: /etc/ansible/roles/sensu-client/
    docker:
      - image: williamyeh/ansible:centos7
    steps:
      - checkout
      - run:
          name: Install sensu-client deps
          command: yum install -y proctools
      - run:
          name: run tests
          command: |
            ansible-playbook -v --connection=local -i localhost, tests/playbook.yml
workflows:
  version: 2
  distro_tests:
      jobs:
        - debian9
        - centos7
