version: 2.0
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - restore_cache:
          #keys:
              #- v1-dependencies-{{ .Branch }}-{{ checksum "tests/requirements.txt" }}
          key:
            - v1-dependencies-
      - run:
          name: Install Python deps in a venv
          command: |
            apt-get update -qq
            apt-get install -y --no-install-recommends virtualenv python-pip python-dev build-essential libffi-dev libssl-dev libpq-dev net-tools gpg
            virtualenv venv
            source venv/bin/activate
            pip install -r tests/requirements.txt
      - save_cache:
          paths:
            - venv
          key: v1-dependencies-{{ .Branch }}-{{ checksum "tests/requirements.txt" }}
      - run:
          name: run tests
          command: |
            source venv/bin/activate
            mkdir -p /etc/ansible/roles/sensu-client && cp -r ~/repo/* /etc/ansible/roles/sensu-client/
            cd tests/
            ansible-playbook -v --connection=local -i localhost, playbook.yml
