version: 2.0
jobs:
  debian8:
    working_directory: /etc/ansible/roles/sensu-client/
    docker:
      - image: williamyeh/ansible:debian8
    steps:
      - checkout
      - run:
          name: Install sensu-client deps
          command: apt-get update -qq && apt-get install -y --no-install-recommends procps
      - run:
          name: run tests
          command: |
            ansible-playbook -v --connection=local -i localhost, tests/playbook.yml
  debian9:
    working_directory: /etc/ansible/roles/sensu-client/
    docker:
      - image: williamyeh/ansible:debian9
    steps:
      - checkout
      - run:
          name: Install sensu-client deps
          command: apt-get update -qq && apt-get install -y --no-install-recommends procps
      - run:
          name: run tests
          command: |
            ansible-playbook -v --connection=local -i localhost, tests/playbook.yml
  ubuntu14.04:
    working_directory: /etc/ansible/roles/sensu-client/
    docker:
      - image: williamyeh/ansible:ubuntu14.04
    steps:
      - checkout
      - run:
          name: Install sensu-client deps
          command: apt-get update -qq && apt-get install -y --no-install-recommends procps
      - run:
          name: run tests
          command: |
            ansible-playbook -v --connection=local -i localhost, tests/playbook.yml
# Unable to test CentOS7 due to SystemD requiring /sys/fs/cgroup/ to be mounted
# in the container which is not allowed via CircleCI's docker integration
# See: https://discuss.circleci.com/t/docker-with-centos7-systemd-container/885
#  centos7:
#    working_directory: /etc/ansible/roles/sensu-client/
#    docker:
#      - image: williamyeh/ansible:centos7
#    steps:
#      - checkout
#      - run:
#          name: run tests
#          command: |
#            ansible-playbook -v --connection=local -i localhost, tests/playbook.yml
workflows:
  version: 2
  distro_tests:
      jobs:
        - debian8
        - debian9
        - ubuntu14.04
#        - centos7
notify:
  webhooks:
    - url: https://galaxy.ansible.com/api/v1/notifications/
