version: 2.0
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: debian:stretch
    steps:
      - checkout

      # Download and cache dependencies
      #- restore_cache:
      #    keys:
      #      - v1-dependencies-{{ .Branch }}-{{ checksum "tests/requirements.txt" }}
      #      # fallback to using the latest cache if no exact match is found
      #      - v1-dependencies-
      - run:
          name: Install Python deps in a venv
          command: |
            apt-get update -qq
            apt-get install -y --no-install-recommends virtualenv python-pip python-dev build-essential libffi-dev libssl-dev libpq-dev net-tools
            virtualenv venv
            source venv/bin/activate
            pip install -r tests/requirements.txt
      - save_cache:
          paths:
            - venv
          key: v1-dependencies-{{ .Branch }}-{{ checksum "tests/requirements.txt" }}
      - run:
          name: run tests
          command: |
            source venv/bin/activate
            mkdir -p /etc/ansible/roles/sensu-client && cp -r ~/repo/ /etc/ansibe/roles/sensu-client/
            cd tests/
            ansible-playbook -v --connection=local -i localhost, playbook.yml
